import {
  Baseline,
  Bold,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Italic,
  Pilcrow,
  Quote,
  Redo2,
  Strikethrough,
  Underline,
  Undo2,
} from "lucide-react";
export const Icons = {
  undo: Undo2,
  redo: Redo2,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  heading4: Heading4,
  heading5: Heading5,
  heading6: Heading6,
  paragraph: Pilcrow,
  quote: Quote,
  bold: Bold,
  underline: Underline,
  italic: Italic,
  strikeThrough: Strikethrough,
  baseLine: Baseline,
} as const;
