import {
  Baseline,
  Bold,
  Ellipsis,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Image,
  Indent,
  Italic,
  Link,
  List,
  ListOrdered,
  MoreHorizontal,
  Outdent,
  Palette,
  Pilcrow,
  Quote,
  Redo2,
  Strikethrough,
  TableIcon,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignStart,
  Underline,
  Undo2,
  Video,
} from "lucide-react";
export const Icons = {
  undo: Undo2,
  redo: Redo2,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  heading4: Heading4,
  heading5: Heading5,
  heading6: Heading6,
  paragraph: Pilcrow,
  blockquote: Quote,
  bold: Bold,
  underline: Underline,
  italic: Italic,
  strikeThrough: Strikethrough,
  baseLine: Baseline,
  palette: Palette,
  justifyStart: TextAlignStart,
  justifyCenter: TextAlignCenter,
  justifyEnd: TextAlignEnd,
  link: Link,
  image: Image,
  video: Video,
  ellipsis: Ellipsis,
  moreHorizontal: MoreHorizontal,
  orderList: ListOrdered,
  list: List,
  indent: Indent,
  outdent: Outdent,
  table: TableIcon,
} as const;
